### ISSUE TITLE
how to linking a product to an offer by api?

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#4238] opened 2021-03-05 10:16 UTC
Dear Allegro team,

Recently, the platform requires stores to increase the relevance of product quotation to 25%. Due to too many advertisements,does the platform have an automatic interface or batch operation? 
That would be great！

Look forward to your reply! Have a good day!
![image](https://user-images.githubusercontent.com/72594584/110101569-afc3f980-7dde-11eb-9585-9bafccbd849c.png)
![image](https://user-images.githubusercontent.com/72594584/110101585-b6527100-7dde-11eb-902e-99268c28eed8.png)

**Comment by PrzemyslawLukanowski** [comment] 2021-03-05 11:36
At the moment, you can choose one of two approaches to assign a product to your offer via API.
POST /sale/products-offers - thanks to which you can list with one request:
- an active offer assigned to a product, which already exists in our database;
- an active offer assigned to a product, which is not in our database.

This process is described in detail in [our guide](https://developer.allegro.pl/en/product_offers/). But as you can see - it will work only for listing new offers. We plan to add a new functionality, you will be able to add product.id to your existing offers using the [PATCH ](https://developer.allegro.pl/en/product_offers/#how-to-edit-an-offer)method. We will write more information about it on our news page. 

The second approach is more complex - you need to search for a specific product via GET /sale/products, then retrieve the product data using GET /sale/product/{productID} and after that - assign a product to the listed offer via PUT /sale/offers/{offerID}. You can also find more information about this process in [our guide](https://developer.allegro.pl/en/productization/).

**Comment by rovingsoul** [comment] 2021-03-08 08:26
An error occured when I linking product.
![image](https://user-images.githubusercontent.com/9605995/110293794-fbb6ae80-8029-11eb-8944-7de3a379586a.png)
![image](https://user-images.githubusercontent.com/9605995/110293770-f22d4680-8029-11eb-863d-d83bb6891b34.png)
It returns empty result when checking the ean(0086547107327) via the api(https://api.allegro.pl/sale/products?ean=0086547107327) 
![image](https://user-images.githubusercontent.com/9605995/110293843-0a9d6100-802a-11eb-9c49-f0db580452e8.png)

**Comment by PrzemyslawLukanowski** [comment] 2021-03-08 08:48
This issue is connected with the functionality on our website, so please report this problem via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). On our forum, we support technical problems related to API resources.

**Comment by bingnew** [comment] 2021-03-12 01:48
I'm sorry to disturb you again.I click the contact form for help on Tuesday, but I haven't got a reply. Because I can't relate to the advertisement, all the newly uploaded advertisements failed. This problem is very serious. I look forward to getting help as soon as possible. Thank you!
![attached](https://user-images.githubusercontent.com/72594584/110879433-f1413100-8317-11eb-8c30-7743d44c189f.jpg)

**Comment by PrzemyslawLukanowski** [comment] 2021-03-12 10:03
As I can see in our logs, you cannot list new offers because you have sell blocked on your account. This case is also beyond API, so please use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) to find the reason for it and what you should do to unlock sales.

**Comment by bingnew** [comment] 2021-03-16 05:09
In no block account, also found this problem, please help query the reason.
Now account can't link to the product, new advertisement can't upload successfully, look forward to your reply as soon as possible.
![image](https://user-images.githubusercontent.com/72594584/111258734-844fd300-8658-11eb-8bb1-bd8dc465620f.png)
![image](https://user-images.githubusercontent.com/72594584/111258739-86b22d00-8658-11eb-999b-1f5a6daca3fe.png)
It returns empty result when checking the ean(0603215037504) via the api(https://api.allegro.pl/sale/products?ean=0603215037504)
![image](https://user-images.githubusercontent.com/72594584/111258770-97fb3980-8658-11eb-9e85-1d1ac27021b6.png)

**Comment by bingnew** [comment] 2021-03-16 05:16
We have never used this ean before. May it be used by other stores? If so, is there an interface to query which ean has been used?

**Comment by PrzemyslawLukanowski** [comment] 2021-03-16 10:48
This message about EAN is invalid and it's not relevant in your case, we will change it in the near future. The problem is with parameters in your offers - we found a product in our database with similar ones but in another category. I assume it's because you are using the same values for manufacturer code and brand in multiple offers. Try to change the manufacturer code to a proper value.

**Closed** 2021-04-22 11:16 UTC
Labels: brak_odpowiedzi, productization
