### ISSUE TITLE
creating test offers on allegro sandbox

### ISSUE THREAD

**Issue by ahmed624** [allegro/allegro-api#3731] opened 2020-10-01 15:28 UTC
Hello everyone,

I have a seller's account at allegro and I have registered and integrated my app with at the allegro sandbox and I am able to fetch application, user tokens.

now i want to create a couple of test orders at allegro sandbox so that i can test the downloading,dispatch, refund of orders through my app. 

can you tell me how to post test orders on allegro? they say that i need to create some offers first to place order against. i have been trying to create offers through POSTMAN but it returns json parsing error. can someone send me a sample json to create a basic offer with a new product that is not in their database. and how can i then post orders against those offers to test the order APIs.

**Comment by AureliuszBrussy** [comment] 2020-10-02 06:31
Please, see our [guide](https://developer.allegro.pl/en/product_offers/#how-to-list-an-offer-assigned-to-a-product-that-is-not-in-our-database) in which we explain how to list an offer assigned to a product that is not in our database with one request. You can also check guides about [listing an offer](https://developer.allegro.pl/en/sale/) and [assigning offers to a products](https://developer.allegro.pl/en/productization/). 

To test your orders - create a new Sandbox account from which you will place orders.

You can also send here your request in curl format (with token removed) - I will check what is missing.

**Comment by ahmed624** [comment] 2020-10-02 08:02
Thanks for the response Aureliusz, 

so to test orders i need to create the offer first. (so that i can create orders using my buyer's account against the created offer) I am using the following JSON to create a dummy offer on my sandbox;

{
    "product": {
        "name":"Produkt testowy",
            "category":{
                    "id":"258020"
            },
              "parameters":[
            {
                "id": "224017",
                "values": [
                    "test 1587459230"
                ]
            },
            {
                "id": "202749",
                "values": [
                    "5.9"
                ]
            },
            {
                "id": "202869",
                "values": [
                    "512 GB"
                ]
            },
            {
                "id": "202829",
                "valuesIds": [
                    "202829_1"
                ]
            },
            {
                "id": "202685",
                "valuesIds": [
                    "202685_212929"
                ]
            },
            {
                "id": "127448",
                "valuesIds": [
                    "127448_2"
                ]
            },
            {
                "id": "202865",
                "valuesIds": [
                    "202865_214109"
                ]
            },
            {
                "id": "4388",
                "valuesIds": [
                    "4388_1"
                ]
            },
            {
                "id": "202717",
                "values": [
                    100
                ]
            },
            {
                "id": "219",
                "values": [
                    "Bluetooth"
                ]
            },
            {
                "id": "202821",
                "values": [
                    "Dual SIM"
                ]
            }
        ]
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    }
}

and the response that i get is 

{
    "errors": [
        {
            "code": "ShippingRatesNotFoundException",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "delivery.shippingRates",
            "userMessage": "The user does not have a shipping rates named: default."
        }
    ]
}

is there any default shipping rate setting at allegro thats i can use in this request? or how are couriers and shipping rates managed here?

**Comment by ahmed624** [comment] 2020-10-02 08:53
and when i try to include any shipping id it gives the internal server error

**Request:**

{
    "product": {
        "name":"Produkt testowy",
        "category":{
            "id":"258020"
        },
        "parameters":[
        {
            "id": "224017",
            "values": [
                "test 1587459230"
            ]
        },
        {
            "id": "202749",
            "values": [
                "5.9"
            ]
        },
        {
            "id": "202869",
            "values": [
                "512 GB"
            ]
        },
        {
            "id": "202829",
            "valuesIds": [
                "202829_1"
            ]
        },
        {
            "id": "202685",
            "valuesIds": [
                "202685_212929"
            ]
        },
        {
            "id": "127448",
            "valuesIds": [
                "127448_2"
            ]
        },
        {
            "id": "202865",
            "valuesIds": [
                "202865_214109"
            ]
        },
        {
            "id": "4388",
            "valuesIds": [
                "4388_1"
            ]
        },
        {
            "id": "202717",
            "values": [
                100
            ]
        },
        {
            "id": "219",
            "values": [
                "Bluetooth"
            ]
        },
        {
            "id": "202821",
            "values": [
                "Dual SIM"
            ]
        }
    ]
    },
    "delivery": {
        "shippingRates": {
            "id": "862347c4-b2b0-42d4-b84a-1db01509a69d"
         }
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    }
}

**Response:**

{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}

**Comment by AureliuszBrussy** [comment] 2020-10-02 09:03
First, you need to create shipping rates by using [POST /sale/shipping-rates](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST), and if you have a company account - you also need to create return policy ([POST /after-sales-service-conditions/return-policies](https://developer.allegro.pl/documentation/#operation/createAfterSalesServiceReturnPolicyUsingPOST)) and complaints policy ([POST /after-sales-service-conditions/implied-warranties](https://developer.allegro.pl/documentation/#operation/createAfterSalesServiceImpliedWarrantyUsingPOST)).

If the name of this offer terms will be "default" ("name": "default") - we are automatically using them in offer when you are using POST /sale/product-offers.

You can also create offer terms in the appropriate [tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-dostawy) on the site.

Hint - if you want to get the correct structure of an offer to use [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) resource, you can list offer via [allegro.pl.allegrosandbox.pl](https://allegro.pl.allegrosandbox.pl/offer/) and then download the offer using [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Then, if you want to use payload from response to list offer via [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) - just remove **id** and **publication.createdAt** fields.

**Comment by AureliuszBrussy** [comment] 2020-10-02 09:58
@ahmed624 it looks like you are using **client_credentials** flow to authorize. This is an authorization method without the user context. You should use another authorization method, for example [code flow](https://developer.allegro.pl/en/auth/#app). All authorization methods are described in our [guide](https://developer.allegro.pl/en/).

**Comment by ahmed624** [comment] 2020-10-02 10:04
Thanks for the prompt response Aureliusz,

We are using the device flow for auth instead of the code flow. because our application is running in a browser less environment. 

The auth link is sent via email. Can you tell me the difference between code flow, device flow and client credentials and which to choose when ?

**Comment by AureliuszBrussy** [comment] 2020-10-02 11:01
With Client_credentials flow authorization you will get access only to resources marked as “bearer-token-for-application” in the “Authorizations” section in [documentation](https://developer.allegro.pl/en/documentation/). You can use device flow on devices or in apps that do not have a graphic interface, a browser, or other simple mechanisms for entering the text.

Could you send us your full request and response in cURL format via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1)? Please add GitHub thread number - #3731.

**Comment by ahmed624** [comment] 2020-10-02 11:58
yes sure. For categories we are using client_credentials and for other resources like orders etc we use device auth. will share with you complete request on the form.

**Comment by ahmed624** [comment] 2020-10-02 13:55
so first i created the return terms, then warranty information and then complaint terms. also created default delivery settings. 

after that i sent the following **POST** dummy offer **request** to https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

{
    "product": {
        "name":"Produkt testowy",
        "category":{
            "id":"258020"
        },
        "images": [
            "http://www.freepngimg.com/download/lion/3-2-lion-png.png",
            "http://www.freepngimg.com/download/lion/3-2-lion-png.png"
        ],
        "parameters":[
        {
            "id": "224017",
            "values": [
                "test 1587459230"
            ]
        },
        {
            "id": "202749",
            "values": [
                "5.9"
            ]
        },
        {
            "id": "202869",
            "values": [
                "512 GB"
            ]
        },
        {
            "id": "202829",
            "valuesIds": [
                "202829_1"
            ]
        },
        {
            "id": "202685",
            "valuesIds": [
                "202685_212929"
            ]
        },
        {
            "id": "127448",
            "valuesIds": [
                "127448_2"
            ]
        },
        {
            "id": "202865",
            "valuesIds": [
                "202865_214109"
            ]
        },
        {
            "id": "4388",
            "valuesIds": [
                "4388_1"
            ]
        },
        {
            "id": "202717",
            "values": [
                100
            ]
        },
        {
            "id": "219",
            "values": [
                "Bluetooth"
            ]
        },
        {
            "id": "202821",
            "values": [
                "Dual SIM"
            ]
        }
    ]
    },
    "delivery": {
        "shippingRates": {
             "name": "default"
         }
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    }
}

the following **response** was received :
{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}
also provided this information through the contact us form as you said. application number "11377616" ref:_00D24aE05._5003V7u0Wc:ref

**Comment by AureliuszBrussy** [comment] 2020-10-05 06:15
Your request seems correct - the offer should be listed. Can you send me the trace-id of your request and the login of the account from which you are trying to list an offer?

**Comment by ahmed624** [comment] 2020-10-05 06:28
well the login of our company seller account is VoloCommerce. I am using the sandbox.

can you please guide me how cal i tell the trace-id? I was using postman to list this offer.

**Comment by AureliuszBrussy** [comment] 2020-10-05 06:39
Your account is not fully activated - you need to upload any two files in "[Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php)" tab ("choose file" button, then "wyślij do weryfikacji"). After that, listing the offer should be successful.

**Comment by ahmed624** [comment] 2020-10-05 06:45
so you mean to say that to continue my testing i can attach any 2 dummy files for now in the after clicking the button shown in the screen below.
![company_confirmation](https://user-images.githubusercontent.com/59685078/95047740-062dee80-0700-11eb-8c61-5433c048d890.png)

**Comment by AureliuszBrussy** [comment] 2020-10-05 06:48
Yes, you just need to attach any two files by clicking "Choose File".

**Comment by ahmed624** [comment] 2020-10-05 10:33
thanks AureliuszBrussy, I was able to list an offer at allegro thanks to you mate.

Now i want to create orders against this offer so that i can test my orders APIs integration with allegro. like downloads, dispatch refund etc. 

Can you tell me how to create a test order against this offer that i created? FYI i have a buyers account as well as directed by your support earlier.

**Comment by AureliuszBrussy** [comment] 2020-10-05 13:14
Just find your offer and place an order directly on the [allegro.pl.allegrosandbox.pl](https://allegro.pl.allegrosandbox.pl/) website.  You can simulate different variants of orders, returns, etc.

**Comment by ahmed624** [comment] 2020-10-05 13:26
and what parameter can be user to find the offer here? offer id?

**Comment by ahmed624** [comment] 2020-10-05 15:33
okay so when i try to place an order it says i can not place an order on my own product.

when i try to logout and try to place the order it takes me to the login page.

and when i login with my buyer's account it says product not found. 

please see screenshots of both scenarios.

is it because my seller account is on sandbox and buyers account is on live? 

what do i need to do how to fix it?
![buyer_account](https://user-images.githubusercontent.com/59685078/95099908-f20edf00-0749-11eb-8cba-3d53a978fa04.png)
![own_products_error](https://user-images.githubusercontent.com/59685078/95099910-f3400c00-0749-11eb-8a6a-e38fed1ed148.png)

**Comment by AureliuszBrussy** [comment] 2020-10-06 05:44
You should try to search for this offer in a test environment, not in the production environment. [Here's your offer.
](https://allegro.pl.allegrosandbox.pl/oferta/produkt-testowy-7678634013)

**Comment by ahmed624** [comment] 2020-10-06 06:58
so i need to create a buyer's account on sand box to place an order against this offer?

**Comment by AureliuszBrussy** [comment] 2020-10-06 08:15
@ahmed624 yes, exactly. You need to create a buyer's account on [Sandbox](https://allegro.pl.allegrosandbox.pl/). Then search your offer on Sandbox and place an order.

**Comment by ahmed624** [comment] 2020-10-06 09:20
Thanks Brussy will create another account and try to make orders using that, will let you know the results. it would be great if you include all these steps in your docs as well it helps really

**Comment by AureliuszBrussy** [comment] 2020-10-06 12:31
Thank you for the suggestion. If you have some more questions - feel free to ask. I'll try to help.

**Comment by ahmed624** [comment] 2020-10-06 15:34
yes Brussy I will continue to seek your guidance till our integration with Allegro APIs is complete. thank you so much for your support.
We plan to integrate orders and products APIs so that our customers can use our allegro connector. 

so, I was able place to orders on sandbox, then

1. downloaded events using order/events?limit=1000&type=READY_FOR_PROCESSING

2. then fetched order details for each event id using this order/checkout-forms/$checkoutform_id

3. then fulfilled the orders to set status to processing using this order/checkout-forms/" + order.getId() + "/fulfillment"

is this the correct sequence? 

and one more thing why is it downloading the same order again n again? is there a way to stop downloading the order that has already been downloaded?

**Comment by AureliuszBrussy** [comment] 2020-10-07 07:39
Yes, it is a correct sequence. Downloading an event does not mean its disappearance. We hold events for 60 days. You can download the newest events after a particular event, for example: 

`GET /order/events?limit=1000&from{last_seen_event_id}
`

You can sometimes retrieve several events of the same type (which apply to the same payment), in that situation you should check the order id in the checkoutForm object.

**Comment by ahmed624** [comment] 2020-10-07 12:15
yes okay now moving to order delivery (shipment) my understanding is that

1. first change the fulfillment status to sent using PUT order/checkout-forms/{checkoutFormId}/fulfillment

2. then Add a parcel tracking number to the order using POST /order/checkout-forms/{id}/shipments

is this the correct order? and are there any other steps needed to be performed order delivery?

**Comment by AureliuszBrussy** [comment] 2020-10-07 14:10
Yes, this is the correct order, but before you change the order fulfillment status (to the “PROCESSING”, “READY_FOR_SHIPMENT”, “SENT”) or you have not added a tracking number to the order, buyer may cancel the order within 3 days after purchase. When you changing the order fulfillment status via **PUT /order/checkout-forms/{id}/fulfillment**, use an optional parameter - **checkoutForm.revision**. You will be sure that you are changing the order fulfillment status (“fulfillment.status”), which exactly the same copy is in Allegro.

You can also check this [guide](https://developer.allegro.pl/en/orders/) where we describe how to handle situations like overpayment, underpayment, or payment refunds.

**Comment by ahmed624** [comment] 2020-10-07 14:22
yes if you check my message sent yesterday this is the very reason that I change the status to PROCESSING as soon as i fetch the order.

**Comment by ahmed624** [comment] 2020-10-07 17:15
okay so when i try to fulfill the order, I am getting foloowing response can you tell what it is? 

I/O error on PUT request for "https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/9f89c2d1-07db-11eb-9f72-01d2d14a21e7/fulfillment": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server

Data sent for this request was: data being sent to Allegro Service:{"status":"PROCESSING"}

**Comment by ahmed624** [comment] 2020-10-08 10:02
can i have a reason for this error please?

**Comment by AureliuszBrussy** [comment] 2020-10-08 10:17
I checked the logs and I can see that the order status has been changed to "PROCESSING". It seems that the error was returned by your application, not Allegro API.

**Comment by ahmed624** [comment] 2020-10-08 11:13
ahan, can you please tell how can i confirm that the status has been changed or updated ?

**Comment by AureliuszBrussy** [comment] 2020-10-08 11:32
You can check that by using **GET /order/checkout-forms/{checkoutForm_id}** resource. In response you will see the appropriate value in **fulfillment.status** field.

**Comment by ahmed624** [comment] 2020-10-09 09:24
thanks Brussy, yes i was able to change the **fulfillment status** to processing . PFA

but the **order status** is still "ready for processing". PFA

when will the order status change? do i need to do myself? or will it be changed automatically when i change the fulfillment status to sent?
![fulfilment_status](https://user-images.githubusercontent.com/59685078/95566504-136a1680-0a3b-11eb-9ede-9e0437d11f42.png)

**Comment by ahmed624** [comment] 2020-10-09 11:20
or do you think  i dont need to worry about order status at all?

**Comment by AureliuszBrussy** [comment] 2020-10-09 11:59
**READY_FOR_PROCESSING** status means that buyer filled in the shipping form, completed the payment (status “ended”), and selected COD or personal pickup, you can therefore proceed with the order. You cannot change this **status** (you can change only **fulfillment.status**).

There are other statuses, like **BOUGHT**, which means, that customer made the purchase but did not pay for the order. All possible statuses are listed in the [guide](https://developer.allegro.pl/en/orders/#orders-in-allegro-rest-api).

**Comment by ahmed624** [comment] 2020-10-09 13:30
okay now moving on to the order cancel and order refund functionality. 
my understanding is that we can not cancel orders using API only the customer can cancel it before we change the status to processing. 
for orders refund we can use https://api.allegro.pl/payments/refunds
passing payment id and reason fields is mandatory and then 
for partial refunds we pass line items object (by quantity or by amount)
but for full refund we pass delivery object (amount and currency) instead of line items. 
is my understanding correct?

**Comment by ahmed624** [comment] 2020-10-09 14:09
and on making the refund request with the following data 

data being sent to Allegro Service:{"payment":{"id":"1234567890"},"reason":"REFUND","lineItems":[],"delivery":{"value":{"amount":"0"}},"additionalServices":{"value":{"amount":"0"}}}

i received error code 422 with following message 

Unprocessable Entity: [{"errors":[{"code":"VALIDATION_ERROR","message":"Invalid parameter format","details":"Invalid value: null","path":"delivery.value","userMessage":"Invalid parameter format"}]}]

can you please tell the reason ?

**Comment by ahmed624** [comment] 2020-10-12 04:51
please respond so that I can move forward to the stock price updates

**Comment by AureliuszBrussy** [comment] 2020-10-12 09:21
Order can be canceled only by the user. After that, you can mark orders as CANCELLED in **fulfillment.status** field. 

As for refunding: in **value** structure, you need to also pass value the **currency** field:

```
"value": {
      "amount": "0",
      "currency": "PLN"
}
```

If you want to refund payment for all items in the order - you should provide all lineitem.id's. Do not forget about the possible refund of additional costs, such as delivery costs.

**Comment by ahmed624** [comment] 2020-10-12 14:16
okay thanks Brussy after this i have tried to send update price request to the offer that i created earlier.
following steps were performed: 
**URI** used was: https://api.allegro.pl.allegrosandbox.pl/sale/offer-price-change-commands/c6992ef6-4819-4357-a3ac-71907c6376c2

**Request** data: 
data being sent to Allegro Service:{"modification":{"type":"FIXED_PRICE","price":{"amount":"10","currency":"GBP"}},"offerCriteria":[{"offers":[{"id":"306c10d0-0c8e-11eb-bdbf-11335cc828c9"}],"type":"CONTAINS_OFFERS"}]}

**response**:

request HTTP Status Code: 400
BadRequest: 400 Bad request: [<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

**Comment by ahmed624** [comment] 2020-10-12 14:17
can you please tell what I am doing wrong herE? thank you so much for your support any ways Brussy. I just have update stocks and update product request left after this one. and then we will beta release our allegro connector to our customers in the UK

**Comment by ahmed624** [comment] 2020-10-13 08:20
can you please update Brussy as i am stuck on this request.

**Comment by AureliuszBrussy** [comment] 2020-10-13 08:37
You are passing incorrect offer id (306c10d0-0c8e-11eb-bdbf-11335cc828c9). Offer id is shorter, for example: 7678634013. Also, at the moment you should only use "**PLN**" value in the **currency** field.

**Comment by ahmed624** [comment] 2020-10-13 09:12
okay let me update this thing then will get back to you. thanks Brussy

**Comment by ahmed624** [comment] 2020-10-13 14:50
okay so i tried again but its the same result. following is the detail Brussy;

**URI**: https://api.allegro.pl.allegrosandbox.pl/sale/offer-price-change-commands/bac9fd97-5982-4693-96a4-6f43391e7041
**request** data being sent to Allegro Service:{"modification":{"type":"FIXED_PRICE","price":{"amount":"0","currency":"PLN"}},"offerCriteria":[{"offers":[{"id":"7678669681"}],"type":"CONTAINS_OFFERS"}]}
**response**: 
 400 Bad request: [<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
now can you please tell why cant i change my offer price?

**Comment by AureliuszBrussy** [comment] 2020-10-14 06:43
Could you send your full request in a curl format? There is one mistake in your payload - you cannot change the price to 0, but error 400 should not appear in this case.

**Comment by ahmed624** [comment] 2020-10-14 08:38
Hi Brussy ye so the request looks like;

curl -X PUT \
  https://api.allegro.pl.allegrosandbox/sale/offer-price-change-commands/bac9fd97-5982-4693-96a4-6f43391e7041 \
  -H 'Authorization: Bearer {token}' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -d '{
   "modification":{
      "type":"FIXED_PRICE",
      "price":{
         "amount":"0",
         "currency":"PLN"
      }
   },
   "offerCriteria":[
      {
         "offers":[
            {
               "id":"7678669681"
            }
         ],
         "type":"CONTAINS_OFFERS"
      }
   ]
}'

**Comment by ahmed624** [comment] 2020-10-14 08:57
also for offer creation I have a few questions to clear my understanding;

1) I observed that allegro assigns an offer_id and a product_id when we try to create a new offer. can we send our own **product_id** while creating offers? (sale/product-offers) so that we are able to create multiple variants of the same product? my understanding is that each variant has to be created as a separate offer using the same product id.

2) can we create offers in products created by other sellers? like products that already exist on the marketplace and we want to list our offers in them? if yes then whats the mechanism? 

3) is allegro catalog based? like if we try to create a product that already exists will it give an error or accept it as a new product?

**Comment by ahmed624** [comment] 2020-10-14 13:10
were you able to take a look brussy?

**Comment by AureliuszBrussy** [comment] 2020-10-14 14:13
Sorry, but I cannot find the answer to why you get 400 Bad request - your payload and header seems valid. Are you sure that request looks exactly like from sent example?

As for the questions:

1. You can create new products and assign this product to many offers. Read more [here](https://developer.allegro.pl/en/product_offers/#how-to-list-an-offer-assigned-to-a-product-that-is-not-in-our-database).
2. You can use existing products created by other sellers. Just retrieve data of existing product via [GET /sale/products?ean={ean}](https://developer.allegro.pl/documentation/#operation/getSaleProducts). Please, check [our guide](https://developer.allegro.pl/en/productization/#search_details) for more info. Then, if you found the right product - you can [list an offer assigned to a product](https://developer.allegro.pl/en/product_offers/) with one request via [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers).
3. If you try to create a product that already exists - you will get an error with information about an existing product.

**Comment by ahmed624** [comment] 2020-10-15 08:08
Hi Brussy, i made another request for update prices as follows;

**uri** : https://api.allegro.pl.allegrosandbox.pl/sale/offer-price-change-commands/1cc26084-1bc0-49f1-8ee7-841a84277784

**request data:** 

{"modification":{"type":"FIXED_PRICE","price":{"amount":"10","currency":"PLN"}},"offerCriteria":[{"offers":[{"id":"7678669681"}],"type":"CONTAINS_OFFERS"}]}

**Response:** 

HTTP Status Code: 400
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad request: [<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

do you want the token that i used for this request?

**Comment by ahmed624** [comment] 2020-10-15 08:44
one more interesting observation Brussy, when I try to perform the same request through postman, PFA details. it returns 0 in success but when i checked the offer details were updated according to the sent price through postman : / shouldnt success be 1? and its not working with postman anyway as i mentioned in the previous comment. 
![Uploading Screenshot from 2020-10-15 13-42-22.png…]()

**Comment by ahmed624** [comment] 2020-10-15 08:46
![Screenshot from 2020-10-15 13-42-22](https://user-images.githubusercontent.com/59685078/96099580-d5fb0280-0eec-11eb-905f-011c2d723443.png)

**Comment by AureliuszBrussy** [comment] 2020-10-15 09:21
Allegro identifies that the product exists base on the EAN and other parameters that uniquely identify the product. 

The price change command works asynchronously, so to get its result use [GET /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandStatusUsingGET) or [GET /sale/offer-price-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET). Use the same **commandId** as in the PUT method.


As you can see - the command works fine in Postman, it seems like the problem is with your implementation.

**Comment by ahmed624** [comment] 2020-10-15 09:23
okay thanks let me check the headers and stuff.

**Comment by ahmed624** [comment] 2020-10-15 13:13
yes its working fine now. thanks Brussy, i'll finalize all the APIs before passing them on to our QA. will get back to you on this thread if there is any other missing piece. cant thank you enough for your support.

**Comment by ahmed624** [comment] 2021-03-05 16:23
Hi Brussy,

We are in the process our releasing our Allegro connector App to our customers, can you please confirm that the same app credentials (token) can be shared across our customers?  or does every customer needs to have a separate app?

**Comment by AureliuszBrussy** [comment] 2021-03-08 06:57
One app can be used by multiple customers. You do not need to create a separate application (Client_ID).

**Comment by ahmed624** [comment] 2021-03-08 07:18
oh okay so what I understand is that the same client id (auth url basically) can be used by multiple customers and allegro will issue different access tokens to them -to uniquely identify which seller is calling the API?

**Comment by AureliuszBrussy** [comment] 2021-03-08 07:24
Yes, exactly, every user will get unique access tokens.

**Comment by ahmed624** [comment] 2021-03-08 07:27
thanks Brussy, you have been great help. will seek your guidance from time to time during this production roll out process.

**Comment by ahmed624** [comment] 2021-03-15 09:31
Hi Brussy, 

I am trying to list to allegro as follow;

uri: https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

just the authorization header is being sent containing the bearer token. 

but the response is as follows;

HTTP Status Code: 406

{"errors":
[{"code":"NotAcceptableException",
"message":"Not acceptable representation requested. Please check 'Accept' request header","
details":null,"path":null,
"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

can you tell me why this error comes when i am not sending any accept header at all : /

**Comment by AureliuszBrussy** [comment] 2021-03-15 10:07
In this case, you need to include in you request 2 additional headers (besides authorization header):

- 'Accept: application/vnd.allegro.beta.v2+json'
- 'Content-Type: application/vnd.allegro.beta.v2+json'

**Comment by ahmed624** [comment] 2021-03-15 12:23
okay thanks Brussy.We are in the QA stage at the moment so just testing different scenarios.

**Comment by ahmed624** [comment] 2021-03-26 16:12
Hi Brussy,

We are in the phase of QA and trying to list a product through our customer application but allegro is rejecting the html in description can you please tell the reason mate. the details are;

uri used : https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

Data sent to allegro:
{
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "1.99",
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 1,
    "unit": "UNIT"
  },
  "publication": {
    "status": "ACTIVE"
  },
  "images": [
    "http://images.esellerpro.com/10101/I/89/TEST.png"
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<html>\n  <head>\n    \n  \n<style type=\"text/css\">\n\nBASE_SIZE 14\nBASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 12 BASE_SIZE 12 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 BASE_SIZE 14 \n</style>\n</head>\n\n  <body>\n    <p>\n      This is a car sticker.\n    </p>\n\n    <p>\n      \n    </p>\n\n    <p>\n      Test listing, please do not buy.\n    </p>\n\n  </body>\n\n</html>\n\n"
          }
        ]
      }
    ]
  },
  "name": "Car Sticker - Test Do Not Buy",
  "external": {
    "id": "Marketplace-CarSticker1"
  },
  "product": {
    "ean": "5093265586551",
    "name": "Car Sticker - Test Do Not Buy",
    "category": {
      "id": "253778"
    },
    "images": [
      "http://images.esellerpro.com/10101/I/89/TEST.png"
    ],
    "parameters": [
      {
        "id": "11323",
        "values": [
          "11323_1"
        ]
      }
    ]
  },
  "delivery": {
    "shippingRates": {
      "id": "a1b813f2-dd32-488b-bc60-fb9eee59f15b"
    }
  }
}

headers:

{"Accept":"application/vnd.allegro.beta.v2+json","Content-Type":"application/vnd.allegro.beta.v2+json"}

Response from Allegro:

422 Unprocessable Entity: [{"errors":[{"code":"VALIDATION_ERROR","message":"Invalid tag \"html\", expected one of {h1, h2, p, ul, ol}","details":"Invalid value: <html>\n  <head>\n    \n  \n<style type=\"text/css\">\n\nBASE_SIZE... (778 bytes)]

**Comment by AureliuszBrussy** [comment] 2021-03-29 06:33
You can use in description only the following HTML tags:
- h1 - title,
- h2 - subtitle,
- p - paragraph,
- ul - unordered (bulleted) list,
- ol - ordered list,
- li - list item,
- b - bold.

If any other HTML tags appear in the description - we will return error 422.

You can read more about offer content in [our guide](https://developer.allegro.pl/en/sale/#5-offer-content).

**Comment by ahmed624** [comment] 2021-03-29 07:17
okay thanks Brussy. will trim the html accordingly.

**Comment by ahmed624** [comment] 2021-04-15 12:08
Hi Brussy, so after sorting out the html issue. now something seems to be causing issues with category feature  data. 

Request:

{"sellingMode":{"format":"BUY_NOW","price":{"amount":"1.99","currency":"PLN"}},"stock":{"available":0,"unit":"UNIT"},"publication":{"status":"ACTIVE"},"images":["http://images.esellerpro.com/10101/I/89/TEST.png"],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p> This is a car sticker </p> \n<p> Test listing, please do not buy. </p>"}]}]},"name":"Car Sticker - Test Do Not Buy","external":{"id":"Marketplace-CarSticker1"},"product":{"ean":"5093265586551","name":"Car Sticker - Test Do Not Buy","category":{"id":"253778"},"images":["http://images.esellerpro.com/10101/I/89/TEST.png"],"parameters":[{"id":"11323","values":["11323_1"]}]},"delivery":{"shippingRates":{"id":"a1b813f2-dd32-488b-bc60-fb9eee59f15b"}}}

Response:

422 Unprocessable Entity: [{"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"","userMessage":"Given parameter id `11323:State` should no have been passed as `product` parameter."}]}]


can you please guide me what needs to be changed here?

**Comment by ahmed624** [comment] 2021-04-15 12:44
Brussy I forgot to mention the URI used, its;

uri:https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

**Comment by AureliuszBrussy** [comment] 2021-04-15 12:48
You should pass "State" parameter (id 11323) outside of the "**product**" object. This is one of the offer parameters. Please, check [our guide](https://developer.allegro.pl/en/product_offers/#how-to-set-offer-parameters), where we write about offer parameters (with example).

**Comment by ahmed624** [comment] 2021-04-15 12:55
thanks Brussy but how do we know that which parameter is offer based and which one is product based?

do you have any examples for both of them please?

**Comment by AureliuszBrussy** [comment] 2021-04-15 12:59
You can find out which parameters are for offer and which for product in the response for [GET /sale/categories/{categoryID}/parameter](https://developer.allegro.pl/en/documentation/#operation/getFlatParametersUsingGET_2) in options.describesProduct field:

- true - product parameter,
- false - offer parameter.

**Comment by ahmed624** [comment] 2021-05-05 20:24
Hi Brussy,

A question about the partial refunds at Allegro, our QA tried to perform a partial refund. following is the detail;

**uri:**

https://api.allegro.pl.allegrosandbox.pl/payments/refunds

**Request:**

{
  "payment": {
    "id": "27b0bb21-ad98-11eb-9b9b-25084ea5abc7"
  },
  "reason": "PAID_VALUE_TOO_LOW",
  "lineItems": [
    {
      "id": "271e6630-ad98-11eb-ac8a-559691003704",
      "type": "QUANTITY",
      "quantity": 1
    }
  ],
  "delivery": {
    "value": {
      "amount": "0.0",
      "currency": "PLN"
    }
  },
  "additionalServices": {
    "value": {
      "amount": "0.0",
      "currency": "PLN"
    }
  }
}

**Response:**

{
  "id": "3d1a5329-adc5-11eb-b1b9-d758640af4f3",
  "payment": {
    "id": "27b0bb21-ad98-11eb-9b9b-25084ea5abc7"
  },
  "reason": "PAID_VALUE_TOO_LOW",
  "status": "NEW",
  "createdAt": "2021-05-05T17:13:41.362Z",
  "totalValue": {
    "amount": "2.00",
    "currency": "PLN"
  },
  "lineItems": [
    {
      "id": "271e6630-ad98-11eb-ac8a-559691003704",
      "type": "QUANTITY",
      "quantity": 1
    }
  ],
  "surcharges": [
    
  ]
}

We tried to perform a partial refund by quantity by providing the item id and its quantity but the entire item was refunded on Allegro. Can you please guide here?

**Comment by ahmed624** [comment] 2021-05-06 09:49
is there something that we need to change here for the partial refunds Brussy?

**Comment by AureliuszBrussy** [comment] 2021-05-06 11:04
If you want to refund only a partial amount - you should set **"AMOUNT"** type in **lineItems[].type** field and and instead of the **lineItems[].quantity**, you should use **lineItems[].amount** field. Please check [our guide](https://developer.allegro.pl/en/orders/#how-to-refund-a-payment) to get more details.

**Comment by ahmed624** [comment] 2021-05-06 19:23
so now my understanding is that partial refunds can be performed by amount only and not by quantity?

**Comment by AureliuszBrussy** [comment] 2021-05-07 06:07
If you indicate the quantity, we will refund the full amount client paid for the item.

**Closed** 2021-06-13 07:00 UTC
Labels: brak_odpowiedzi, offer, orders, sandbox

**Comment by AureliuszBrussy** [comment] 2021-08-30 05:07
You need to use [GET /sale/categories?parent.id=**{categoryId}**](https://developer.allegro.pl/en/documentation/#operation/getCategoryUsingGET_1) to retrieve a list of subcategories that belong to the category provided as parent.id parameter. If you use **GET /sale/categories** without providing any category, you will retrieve only IDs of the main Allegro categories. 
Use the identifiers to get to the lowest tier category.
