### ISSUE TITLE
Allegro CZ - API

### ISSUE THREAD

**Issue by Ricomsecure** [allegro/allegro-api#7202] opened 2023-06-12 05:11 UTC
My question concern the connection of products via API, to Allegro CZ.
 
This is the question that interest me - we can't upload products to Allegro CZ via API.
 
**adding a new product- this doesn't work:**

stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => AccessDenied [message] => Access is denied [details] => [path] => [userMessage] => No access to the specified resource. ) ) )

**Comment by MartaNowaczyk** [comment] 2023-06-12 05:57
Please give me the trace-id for the response with this error so I can verify it.

**Comment by Ricomsecure** [comment] 2023-06-12 06:23
Sorry, but we have no available traceid for this. The only response from server we get when adding a product is this:

stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => AccessDenied [message] => Access is denied [details] => [path] => [userMessage] => No access to the specified resource. ) ) )

**Comment by Ricomsecure** [comment] 2023-06-12 06:24
Sorry, but we have no available traceid for this. The only response from server we get when adding a product is this:

stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => AccessDenied [message] => Access is denied [details] => [path] => [userMessage] => No access to the specified resource. ) ) )

**Comment by Ricomsecure** [comment] 2023-06-12 09:00
Ok, I wrote you via the contact form.

**Comment by MartaNowaczyk** [comment] 2023-06-12 11:16
Thank you, as soon as I receive this information and verify it I will let you know.

**Comment by Ricomsecure** [comment] 2023-06-12 11:25
ok thank you, i will wait.

**Comment by Ricomsecure** [comment] 2023-06-15 09:27
Hi i still wait to your answer.

**Comment by Ricomsecure** [comment] 2023-06-15 11:54
it is:  "34003460" ref:_00D24aE05._5003VZyeOd:ref

**Comment by MartaNowaczyk** [comment] 2023-06-16 10:33
As far as I can see the problem is the token. Too bad you didn't provide the full token in the request or at least the clientId you are using, but you can still do it in the same thread. Make sure you have the right scope allegro:api:sale:offers:write.

**Comment by Ricomsecure** [comment] 2023-06-19 06:07
We have everything set up correctly as far as I can see.

Client ID: 65b404ffae98494eaf85c609e8f384e3

Again - all calls like get shipping_rates, get imlied_warranties, get return_policies and even get order events are working correctly. We are using one token for it. Refreshing tokens works correctly, too. And we use the same token for creating product and offer sale/product-offers and we still get result "Access is denied".

When we ask for categories tree (with client ID above) we still get in in Polish, not in Czech.

 



 

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

**Comment by AureliuszBrussy** [comment] 2023-06-19 06:21
@Ricomsecure I checked our logs - the scope [allegro:api:sale:offers:write] is missing in the access token you are trying to use. You need to generate a new access token with the appropriate scope.  You can read more about scopes in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#scope-in-the-allegro-api). 

To get the category tree in Czech, make sure you send the value "cs-CZ" in the Accept-Language header.

**Comment by Ricomsecure** [comment] 2023-06-20 11:09
Hi,

 

thank you very much, it works.

 

I have other question.

 

Are the parameters available in Czech? We currently only see parameters in Polish.

 

We use the correct token, id of the Czech category and also Accept-Language: cs-CZ, so that should be all.

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

tel: +420 725 846 785

www.oxe.cz

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

**Comment by MartaNowaczyk** [comment] 2023-06-20 12:35
Accept-Language: cs-CZ should return parameters in Czech.  Please provide the id of the affected category.

**Comment by Ricomsecure** [comment] 2023-06-20 12:38
https://api.allegro.pl/sale/categories/252387/parameters
 
curl -X GET https://api.allegro.pl/sale/categories/252387/parameters
-H "Authorization: Bearer xxxxxxxxxxxx" 
-H "Accept: application/vnd.allegro.public.v1+json" 
-H "Content-Type: application/x-www-form-urlencoded"  
-H "Accept-Language: cs-CZ"

 

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

tel: +420 725 846 785

www.oxe.cz

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

**Comment by MartaNowaczyk** [comment] 2023-06-21 06:27
Please provide the trace-id you receive in the response header. I'll check for sure that you are providing the correct Accept-Language. In addition, you can also paste some of the data from the response that is returned after your request.
For the category you specified, I have the correct data:
```
"parameters": [
        {
            "id": "11323",
            "name": "Stav zboží",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": false,
            "requiredIf": null,
            "displayedIf": null,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": true,
                "ambiguousValueId": null,
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                "describesProduct": false,
                "customValuesEnabled": false
            },
            "dictionary": [
                {
                    "id": "11323_1",
                    "value": "Nové",
                    "dependsOnValueIds": []
                },
                {
                    "id": "11323_2",
                    "value": "Použité",
                    "dependsOnValueIds": []
                }
            ],
...
}
```

**Comment by Ricomsecure** [comment] 2023-06-21 06:42
It works.

 

Thank you very much.

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

tel: +420 725 846 785

www.oxe.cz

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

**Comment by Ricomsecure** [comment] 2023-06-27 20:04
Hi,

 

We have a problem with product ID 586410. It keeps telling us that a product with the given product code already exists.:

 

[errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => PARAMETER_MISMATCH
                    [message] => The provided parameter 'Model'(237206) value (OXE Gepard II + OXE DV29) does not match the existing parameter value (SET10-1+DV29)
                    [details] => 
                    [path] => productSet[0].product.parameters
                    [userMessage] => Zadaný produkt již existuje. Uvedený parametr „Model“ s hodnotou „OXE Gepard II + OXE DV29“ neodpovídá produktovému parametru „SET10-1+DV29“.
                )
 
        )

 

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

tel: +420 725 846 785

www.oxe.cz

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

 



 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, June 21, 2023 8:43 AM
To: 'allegro/allegro-api' ***@***.***>; 'allegro/allegro-api' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [allegro/allegro-api] Allegro CZ - API (Issue #7202)

 

It works.

 

Thank you very much.

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

tel: +420 725 846 785

www.oxe.cz

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

**Comment by MartaNowaczyk** [comment] 2023-06-28 05:54
Based on the set of parameters you sent us, we recognized that this product already exists in our Product Catalog, but has a different value in the parameter "Model"(237206). After changing the value in this parameter to the one expected by us ("SET10-1+DV29") - the listing will be successful.

If there are incorrect product data in the product in our Catalog - you can submit a proposal for change. You can read more about it [in our guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-report-incorrect-data-in-a-product).

In addition, according to our [GitHub forum rules](https://github.com/allegro/allegro-api/wiki), create a new thread with each new issue.

**Comment by Ricomsecure** [comment] 2023-06-29 12:14
This are responses we get from allegro:

1) setting up a new product (we do not understand where is that code from, we do not have such product under this seller account):

 [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => PARAMETER_MISMATCH
                    [message] => The provided parameter 'Model'(237206) value (OXE Gepard II + OXE DV29) does not match the existing parameter value (SET10-1+DV29)
                    [details] => 
                    [path] => productSet[0].product.parameters
                    [userMessage] => Zadaný produkt již existuje. Uvedený parametr „Model“ s hodnotou „OXE Gepard II + OXE DV29“ neodpovídá produktovému parametru „SET10-1+DV29“.
                )
 
        )
 
2) when we try the same call, only with allegro.pl product id (it has that product code), we get response:
 
 (
            [code] => AccessDeniedException
            [message] => Client is not allowed to execute this command
            [details] => AccessDeniedException
            [path] => /sale/offers/13527755108
            [userMessage] => Zákazník nemá oprávnění k provádění těchto pokynů
        )

 

3) when we try another prodct response is:
 
(
            [code] => VALIDATION_ERROR
            [message] => Platforms other than allegro.pl only support offers with a product linked.
            [details] => ConstraintViolationException.BaseProductizedMarketplaceWithProductOnly
            [path] => null
            [userMessage] => Platformy jiné než allegro.pl podporují pouze nabídky propojené s produktem.
        )
It looks completely random.

 

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

tel: +420 725 846 785

www.oxe.cz

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

**Comment by MartaNowaczyk** [comment] 2023-06-30 05:26
1. The product exists in the general Allegro Product Catalog, and is not assigned to an account.

2. Make sure you are providing the correct [scope](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#scope-in-the-allegro-api) allegro:api:sale:offers:write and that you are not using an authorization type [client_credentials ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow)when listing, which does not have a user context. See our [documentation](https://developer.allegro.pl/documentation) for a proper indication of what type of authorization is required for the resource:

- bearer-token-for-user ([code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow)).

3. Here it looks like you would like to list an offer without a product, and on allegro.cz you cannot list an offer without a related product.

For verification I need the reqests and responses you send. Otherwise it is difficult to verify it accurately. You can also log the trace-id that you find in the response header and send it to us in case of problems.

**Comment by Ricomsecure** [comment] 2023-07-10 09:37
Hi,

 

I have a few other questions.

 

1.	We manage to upload products to Allegro CZ, but some are without a product description, some are uploaded with a CZ description, but it does not match the product description we send.

 

What about the Czech product descriptions, please?

 

 

2.	Furthermore, we cannot upload products that we do not have on Allegro PL. Is it the case that we must first upload the product to Allegro PL and only then can we add it to Allegro CZ via the API? Or is it possible to set up a product only on Allegro CZ?

 

S přáním hezkého dne

 

Ing. Ondřej Přibyl 

Web Support 

 

e-mail:  ***@***.***> ***@***.***

tel: +420 725 846 785

www.oxe.cz

 

RICOM secure, s.r.o.

Tovární 319, 471 54 Cvikov

**Comment by MartaNowaczyk** [comment] 2023-07-10 11:58
1. If you have a trace-id then provide it to check. the ID of the product you added will also be helpful.

2. We have one product catalog for all marketplaces of allegro. It is not necessary to add them for each individual site.

**Closed** 2023-07-25 04:27 UTC
Labels: productization, brak_odpowiedzi, marketplaces
