### ISSUE TITLE
Access denied for sale/product-proposals in sandbox

### ISSUE THREAD

**Issue by din1s** [allegro/allegro-api#6017] opened 2022-08-16 06:48 UTC
Hello!

I'm trying to add a product to the test environment, an error is returned "Access denied". I created an authorization token without specifying a scope, It looks like the problem is with account activation. I found a similar thread (https://github.com/allegro/allegro-api/issues/5126) Can you activate our account? Client ID 105468968

**Comment by PrzemyslawLukanowski** [comment] 2022-08-16 07:46
Hi, to list offers via API you need a company account (yours is regular). Please change the type via [this tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by din1s** [comment] 2022-08-16 09:28
Thanks for the answer!
Account type was changed, but the error remains

**Comment by PrzemyslawLukanowski** [comment] 2022-08-16 10:23
Please continue full activation process for selling via [this tab](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty). If error still remains after you finish this, please let me know.

**Comment by din1s** [comment] 2022-08-16 11:01
Everything was filled in, the Access denied error remained

**Comment by PrzemyslawLukanowski** [comment] 2022-08-16 11:44
Ok, I've ended the activation process on our side, and now everything should work.

**Comment by din1s** [comment] 2022-08-17 07:06
Thank you very much, everything worked!

There was one more question. We are adding books, we cannot associate our publishers with the publishers on your system, so we decided to pass the value for the parameter (ID 223541) 223541_305725 (inne). But when adding a product, an error is returned "Nie została podana propozycja wartości do wartości niejednoznacznej w parametrze Wydawnictwo". 

How can we be in such a situation and what to transmit as a publisher?

**Comment by PrzemyslawLukanowski** [comment] 2022-08-17 07:47
In this case, provide your value in the "values" field. Here you can find sample:

```
{
     "id": "23541",                             -- parameter id
     "valuesIds": [
       "23541_305725"                           -- ambiguous value id
     ],
     "values": [ "{Missing publisher value}" ],    -- value, which you want to provide.
                                                 Complete this field.
     "rangeValue": null
}
```

**Comment by din1s** [comment] 2022-08-23 09:57
We want to add more than 100k positions of books in Russian to the catalog, so that it would be easier for customers to search for the books they need, you can create subcategories for yourself as in books in English https://prnt.sc/oabNnVUx2EW_, and we will connect our own with them and load like this?

**Comment by PrzemyslawLukanowski** [comment] 2022-08-23 10:18
Adding subcategories in an existing category is not a topic directly connected with API Allegro, so please use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) in this case.

**Comment by din1s** [comment] 2022-08-26 05:09
Hello!
We are trying to add one trade offer to the working environment and the following error occurs:

> [code] => ConstraintViolationException.MissingRequiredParameters
>                     [message] => Missing required parameters: 248247, 249493
>                     [details] => ConstraintViolationException.MissingRequiredParameters
>                     [path] => parameters
>                     [userMessage] => Uzupełnij parametry obowiązkowe: Rodzaj, Gatunek.

					
The same product was added to the test environment without problems. With what it can be connected?
An example of our request:

{"productSet":[{"product":{"name":"Skazy","category":{"id":"91465"},"id":"a53b7203-d34b-4947-855f-a8ed183e9d91"},"quantity":{"value":1}}],"delivery":{"handlingTime":"PT0S","shippingRates":{"id":"401eb0ba-b9ea-4aa0-a4f2-bd92c684c558","name":"dost"},"additionalInfo":"","shipmentDate":"2022-08-26T00:00:00Z"},"category":{"id":"91465"},"payments":{"invoice":"VAT"},"parametrs":[{"id":248247,"valuesIds":["248247_883389"]},{"id":249493,"valuesIds":["249493_1645911"]}],"afterSalesServices":{"warranty":{"id":"bf074d0f-1c39-43a9-b3d7-fa4b77b3e809","name":"default1"},"returnPolicy":{"id":"bf074d0f-1c39-43a9-b3d7-fa4b77b3e809","name":"default1"},"impliedWarranty":{"id":"bf074d0f-1c39-43a9-b3d7-fa4b77b3e809","name":"default1"}},"sellingMode":{"format":"BUY_NOW","price":{"amount":"97","currency":"PLN"},"minimalPrice":{"amount":"97","currency":"PLN"},"startingPrice":{"amount":"97","currency":"PLN"}},"stock":{"available":"1","unit":"UNIT"}}

**Comment by PrzemyslawLukanowski** [comment] 2022-08-26 06:14
Could you please try to add those parameters in the _productSet.product.parameters_ section? Like in the second example at the beginning of our [tutorial](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA):

```
curl -X POST
  'https://api.allegro.pl/sale/product-offers'
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d '{
    "productSet": [{
        "product": {
            "id": "d26b023c-d52c-44f9-b61a-321eb202792b",
            "parameters": [{
                "id": "202293",
                "valuesIds": [
                    "202293_211441"
                ]
            }]
        }
    }],
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    }
}'
```

There may be some discrepancies between our production and test environment. Once a quarter we update a list of categories and parameters to ensure consistency between these.

**Comment by din1s** [comment] 2022-08-26 06:28
Thanks for the answer! Didn't work, still got error.
The request was like this:
```
{
  "productSet": [
    {
      "product": {
        "name": "Skazy",
        "category": {
          "id": "91465"
        },
        "id": "a53b7203-d34b-4947-855f-a8ed183e9d91",
        "parametrs": [
          {
            "id": 248247,
            "valuesIds": [
              "248247_883389"
            ]
          },
          {
            "id": 249493,
            "valuesIds": [
              "249493_1645911"
            ]
          }
        ]
      },
      "quantity": {
        "value": 1
      }
    }
  ],
  "delivery": {
    "handlingTime": "PT0S",
    "shippingRates": {
      "id": "401eb0ba-b9ea-4aa0-a4f2-bd92c684c558",
      "name": "dost"
    },
    "additionalInfo": "",
    "shipmentDate": "2022-08-26T00:00:00Z"
  },
  "category": {
    "id": "91465"
  },
  "payments": {
    "invoice": "VAT"
  },
  "afterSalesServices": {
    "warranty": {
      "id": "bf074d0f-1c39-43a9-b3d7-fa4b77b3e809",
      "name": "default1"
    },
    "returnPolicy": {
      "id": "707b4c76-a4c7-499b-b5e1-1f8f629edcc3",
      "name": "1"
    },
    "impliedWarranty": {
      "id": "cb99c925-dfa0-4731-9e65-581819181001",
      "name": "1"
    }
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "97",
      "currency": "PLN"
    },
    "minimalPrice": {
      "amount": "97",
      "currency": "PLN"
    },
    "startingPrice": {
      "amount": "97",
      "currency": "PLN"
    }
  },
  "stock": {
    "available": "1",
    "unit": "UNIT"
  }
}
```

**Comment by PrzemyslawLukanowski** [comment] 2022-08-26 06:52
You have a typo in your data - "parametrs" instead of "parameters".

**Comment by din1s** [comment] 2022-08-26 07:43
Thank you, the product has been added. But now the next problem is adding the product to the category https://allegro.pl/kategoria/po-angielsku-pozostale-91485

The error "Nie została podana propozycja wartości do wartości niejednoznacznej w parametrze Okładka" is returned.

We pass all the parameters, the request is as follows:

```
{
  "name": "16 urokov angliyskogo yazyka. Nachalnyy kurs",
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "Dannoe izdanie predstavlyaet soboy nachalnyy kurs angliyskogo yazyka, razrabotannyy Dmitriem Petrovym. V pechatnoy versii kursa dany uprazhneniya, osnovnye pravila proiznosheniya i svedeniya o glagolah. S pomoschyu shestnadcati urokov po metodike Dmitriya Petrova vy smozhete osvoit bazovye algoritmy yazyka, primenit ih na praktike i dovesti do avtomatizma. V pomosch tem, kto zanimaetsya samostoyatelno, predlagaetsya polnyy sbornik klyuchey, t.e. vypolnennyh uprazhneniy. Teper chitateli smogut proverit, pravilno li oni usvoili grammaticheskie pravila, i vnesti neobhodimye korrektivy v process izucheniya yazyka.Nachnite govorit na angliyskom pryamo seychas!</p>"
          }
        ]
      }
    ]
  },
  "category": {
    "id": 91485
  },
  "images": [
    {
      "url": "https://a.allegroimg.com/original/11496a/8502517b4e87a1d133ac173f08aa"
    }
  ],
  "parameters": [
    {
      "id": 11323,
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": 245669,
      "values": [
        "9785041133856"
      ]
    },
    {
      "id": 248247,
      "valuesIds": [
        "248247_883389"
      ]
    },
    {
      "id": 249493,
      "valuesIds": [
        "249493_1645911"
      ]
    },
    {
      "id": 2868,
      "valuesIds": [
        "2868_5"
      ]
    },
    {
      "id": 75,
      "valuesIds": [
        "75_314838"
      ]
    },
    {
      "id": 74,
      "values": [
        "2020"
      ]
    },
    {
      "id": 223545,
      "values": [
        "16 urokov angliyskogo yazyka. Nachalnyy kurs"
      ]
    },
    {
      "id": 223489,
      "values": [
        "Petrov Dmitriy Yurevich"
      ]
    },
    {
      "id": 223541,
      "valuesIds": [
        "223541_305725"
      ],
      "values": [
        "Eksmo"
      ]
    }
  ]
}
```

**Comment by PrzemyslawLukanowski** [comment] 2022-08-26 07:52
In the parameter with id 75 you have selected an ambiguous value. In this case, you should provide your own value in the "values" field, like below:

```
{
   "id": "75",                     
   "valuesIds": [
     "75_314838"                     
   ],
   "values": ["your value"],   
   "rangeValue": null
}
```

But to be honest, in my opinion, there's no need to choose an ambiguous value. I think we return all types of "covers" in the list of available values and you can choose a proper one.

**Comment by din1s** [comment] 2022-08-31 07:53
Good afternoon!
We sent a request from the contact form to the ID for authorization through DCR, more than a week has passed, but there was no answer. Is there any way to speed up this process?

**Comment by PrzemyslawLukanowski** [comment] 2022-08-31 08:11
Hi, we've just received such a request from client ID e6f4557c742e4891815be964ae3***** - is it you? If so, you will receive more details via email.

**Comment by din1s** [comment] 2022-08-31 08:13
Our client ID 3f3f856f695244d5ad810***********

**Comment by PrzemyslawLukanowski** [comment] 2022-08-31 08:18
We haven't received such a request yet. Could you please use the contact form once again and this time add information that the request should be forwarded to the API Team?

**Comment by din1s** [comment] 2022-09-06 08:49
Good afternoon!
Are there any restrictions on the loading of goods by api (per hour / per day / per week)? We downloaded about 80k products and now the speed has decreased.

**Comment by PrzemyslawLukanowski** [comment] 2022-09-06 08:57
The main limit imposed on Client ID is one- 9000 requests per minute. But for selected REST API resources (like, for example GET /sale/products) we have a mechanism that limits the number of requests submitted by a given user. We use the Leaky Bucket algorithm. If you exceed the number of requests per minute (RPM), the response time is extended. This limit is not a constant value, so we cannot reveal information about it.

**Comment by din1s** [comment] 2022-09-08 10:32
Good afternoon!

Can you please tell me if we can disable the offer and remove it? For some reason, at https://api.{environment}/sale/product-offers/{offerId} we can only assign the status ACTIVE and ENDED, the status INACTIVE does not apply. Tell me, what is the reason?

**Comment by PrzemyslawLukanowski** [comment] 2022-09-08 10:46
INACTIVE status is equivalent to offer draft, so once you activate such an offer, you can only change the status to ENDED. Offer in ENDED status can be activated, but if you don't do that within 60 days after the offer ended, we will archive it, and it won't be possible to do anything with such an offer. 
Via [/sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) you can also create offer drafts instead of listing active offers - in your request JSON just add `publication.status` field, like [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#inactive-status).

**Comment by din1s** [comment] 2022-09-08 11:28
Do we understand correctly that offers with ENDED status are automatically deleted after 60 days?

Can we speed it up somehow? We have added some suggestions that we want to remove now. Is this possible with the API?

**Comment by din1s** [comment] 2022-09-09 06:03
Hello!
Can you please tell me if the token renewal works for sandbox?

We are trying to implement the extension of the token according to the example (https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#php), but when we try we get an error:

> {"error":"invalid_client","error_description":"Unauthorized grant type: authorization_code"}

**Comment by PrzemyslawLukanowski** [comment] 2022-09-09 06:34
Yes, refresh tokens work on Sandbox. The link you sent relates to the authorization code flow type of authorization (how to generate access and refresh tokens), not to extending token validity with refresh tokens directly. Please make sure that you changed all of the links to https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize and https://allegro.pl.allegrosandbox.pl/auth/oauth/token.

**Comment by din1s** [comment] 2022-09-15 05:50
Good afternoon!
Found an issue where some trade offers are not created due to the error "The maximum allowed length of the offer title has been exceeded (50 characters, assuming that some letters and symbols are counted as more than 1 character).". But the problem is that the names are less than 50 characters, for example: "Chevrolet Niva. Vypusk s 2002, restay", "Art terapiya. Dzhungli Amazonki. 70 risunk", "Nauchno obrazovatelnaya sessiya k 85 letiyu", etc.

**Comment by PrzemyslawLukanowski** [comment] 2022-09-15 06:42
Hi, we're verifying this issue. I'll let you know when we have more details.

**Comment by din1s** [comment] 2022-09-16 10:18
Good afternoon!
Any news on our issue?

**Comment by PrzemyslawLukanowski** [comment] 2022-09-16 10:33
Unfortunately no, the problem is more complex and seems to be connected with the product names, not the offer titles you provide. Our team is still investigating it.

**Comment by din1s** [comment] 2022-09-19 06:08
Good afternoon.
Since yesterday, our API production authorization has stopped working. We cannot get a response to the token request for an infinitely long time. What information do you need?

**Comment by PrzemyslawLukanowski** [comment] 2022-09-19 06:26
Hello, please send us sample requests via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a). Also, add information that the data refers to GitHub #6017 thread and include the token your trying to use. Are you getting any errors or no response at all?

**Comment by din1s** [comment] 2022-09-19 06:31
Sent.
We receive nothing in response, the request is sent, but no response follows

**Comment by PrzemyslawLukanowski** [comment] 2022-09-19 09:15
We still waiting for the data from the form, it needs to be passed to our department.
In the meantime, I've checked our logs - it seems that your application sends us a lot of requests, but with an invalid device code. Could you please check this issue on your side - is this parameter and its value being sent correctly?

**Comment by din1s** [comment] 2022-09-19 09:31
We have sent an application.

Yes, now sending with the correct code, we have changed the app data for another account

**Comment by PrzemyslawLukanowski** [comment] 2022-09-19 11:07
We are still receiving requests with invalid device codes, for instance - you're trying to use "QOQQunJ8Z7Q8XfuBJtvZKY2NU4vTH***" since yesterday multiple times per minute.

**Comment by din1s** [comment] 2022-09-19 12:22
We have now stopped everything, are the requests still coming?

**Comment by PrzemyslawLukanowski** [comment] 2022-09-19 12:43
No, the last requests were at 14:21.

**Comment by din1s** [comment] 2022-09-26 11:37
Good afternoon. About the length of news headlines?
When adding products, we also encountered a problem, we get an error - You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.

Where can I find these drafts and how can I delete them?

**Comment by din1s** [comment] 2022-09-30 09:05
Good afternoon.
Sorry to bother you, can I find out the approximate time to resolve the issue by the titles of the goods?

**Comment by PrzemyslawLukanowski** [comment] 2022-09-30 09:25
The problem should be fixed within the next two weeks.

**Comment by din1s** [comment] 2022-10-11 11:28
Hello!
Any news on our issue?

**Comment by AureliuszBrussy** [comment] 2022-10-11 11:33
@din1s not yet, we will let you know as soon as the problem is solved. I apologize for the inconvenience.

**Comment by PrzemyslawLukanowski** [comment] 2022-10-17 12:36
@din1s The problem has been solved. Sorry for keeping you waiting for so long.

**Comment by PrzemyslawLukanowski** [comment] 2022-10-18 08:52
No, we support only Polish and English base languages of offers.

**Comment by din1s** [comment] 2022-10-18 09:05
How are books with Cyrillic titles added here https://allegro.pl/listing?string=%D0%BA%D0%BD%D0%B8%D0%B3%D0%B0?

**Comment by PrzemyslawLukanowski** [comment] 2022-10-18 09:22
Sorry for my mistake, it seems I was trying to use one of the characters that were not allowed. You can use Cyrylic and below is the list of all allowed characters:

abcdefghijklmnopqrstuwvxyzäöüøòß0áčěířšťůúýžœæàâçéèêëîïôûùüÿ€×ąćęłńóśźżµ⌀ľÞаурсİРСхÌ±ğÑφмкБвσНбμŐейãĕďŏṣõъňåтӧðūăгβÕÃşÅḥŜñлёКőģėāТņдΦяÐĽōīи0123456789!@[]#$%^&*{}().,,,/\\|? ;~²³`''’´\""\"„"″<>_:-=+0…–°° ‰§ґєжзіїопфцчшщюьАаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЬьЮюЯяĄĆĘŁŃÓŚŹŻÁáČčĎďÉéĚěÍíŇňÓóŘřŠšŤťÚúŮůÝýŽž

**Comment by din1s** [comment] 2022-10-19 09:04
Good afternoon!

We also have a question about changing the status of orders to the status "PICKED_UP". When and under what conditions is this status established? The customer says that the clients' order status is already "order received", and we get the order status "SENT". Why can this be so?

**Comment by PrzemyslawLukanowski** [comment] 2022-10-19 09:08
Hi, you can change this status manually anytime you want via [PUT /order/checkout-forms/{checkoutForm.id}/fulfillment](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#order-fulfillment-status-change), it won't change automatically except the scenario when a merchant has subscription enabled and she/he provides tracking number - then the status will change automatically to SENT if she/he choose this option in the Order settings on our website.

**Comment by din1s** [comment] 2022-10-19 10:21
The customer says that they have everything connected and they transmit track numbers. As we understand, the "Sent" status changes automatically for them, but the "PICKED_UP" status does not. Can the PICKED_UP status change automatically on your side at all?

**Comment by PrzemyslawLukanowski** [comment] 2022-10-19 10:25
Unfortunately not, only the "SENT"/"DISPATCHED" status can be changed that way:

<img width="522" alt="Zrzut ekranu 2022-10-19 o 12 24 47" src="https://user-images.githubusercontent.com/51473661/196665964-798ae9f3-25c6-4911-8786-d3cfd6c22521.png">

**Comment by din1s** [comment] 2022-10-19 11:33
Tried to continue adding products.
Unfortunately, when creating a trade offer, I get the error "The maximum allowed length of a single word in the offer title has been exceeded (30 characters)."

Headings with such a plan "Chitat,risovat,hohotat!", "Organizacionno-tehnologich"

**Comment by din1s** [comment] 2022-10-19 12:34
> Unfortunately not, only the "SENT"/"DISPATCHED" status can be changed that way:
> 
> <img alt="Zrzut ekranu 2022-10-19 o 12 24 47" width="522" src="https://user-images.githubusercontent.com/51473661/196665964-798ae9f3-25c6-4911-8786-d3cfd6c22521.png">

Can you please tell me where these settings are located in the account?

**Comment by PrzemyslawLukanowski** [comment] 2022-10-19 12:52
> Headings with such a plan "Chitat,risovat,hohotat!", "Organizacionno-tehnologich"

You can just add space between "," and "-", for example: "Chitat, risovat, hohotat!"

> Can you please tell me where these settings are located in the account?

It is in [Orders tab](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/), and then "Settings" in the top right corner.

**Comment by din1s** [comment] 2022-10-20 05:29
Good morning.
Unfortunately your advice didn't help. We even removed all symbols except for letters, but still trade offers are not added with the same error "The maximum allowed length of a single word in the offer title has been exceeded (30 characters)."
Product name example:
"Normat pravov obesp vospi"
"Ist relig tayn relig obsch" 
etc.

**Comment by PrzemyslawLukanowski** [comment] 2022-10-20 05:40
Ok, I see, the reason is the length of the words in the product title (not in your offer). I'm passing this issue once again to our team responsible for this service. Sorry once again for inconvenience.

**Comment by din1s** [comment] 2022-10-20 10:05
There is also a question about the delivery status - in the personal account we see that the order has been delivered - https://prnt.sc/vMRoozjbxQh4
But when receiving information on the order via "order/checkout-forms/" we do not see that it has been delivered. How can we get this information?

**Comment by PrzemyslawLukanowski** [comment] 2022-10-21 05:16
When it comes to the problem when too long word names - could you please send me all of the offer titles with which you've received error messages? We need to change all of the product names that have been entered improperly, for example, "Normat.pravov.obesp.vospit.deyat.v VUZah Rossii T.1" (dots instead of empty spaces).

> There is also a question about the delivery status - in the personal account we see that the order has been delivered - https://prnt.sc/vMRoozjbxQh4
> But when receiving information on the order via "order/checkout-forms/" we do not see that it has been delivered. How can we get this information?

This information relates to parcel tracking statuses from the carrier and we don't return it in the order details, this is not the same as seller status in "fulfillment.status" field. You can receive those information only if you shipped parcel via [Ship with Allegro](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV) - the endpoint responsible for this is [GET /order/carriers/{carrierId}/tracking?waybill={waybill}](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-parcels-statuses-history).

**Comment by din1s** [comment] 2022-10-27 08:29
Good afternoon.
List of products for which errors occur:
> 
> Lechenie izbegayuschego/ogranichitelnogo rasstroystva priema pischi  Osnovannaya na seme terapiya
> Organizacionno tehnologicheskoe proektirovanie pri proizvodstve rabot na obektah stroitelstva
> Simptom sindrom diagnoz Bolezni pochek i mochev sis"
> Chitat risovat hohotat!Smeshnye kartin myshki Mashi
> Organizacionno pedagogicheskaya kultura obrazovatelnogo uchrezhdeniya
> Optimal proekt assemblern progr matem algor Lab pr
> Ugolovnoe zakonodat sovr Rossii Proekty probl prog
> V raznyh zhanrah Stati rasskazy esse stihi
> Enciklopedicheskiy slovar spravochnik Vyrazitelnye
> Russkiy tradicionalizm:istorii ideologiya Vyp  VII
> Intermedialnost filologicheskiy kontinent
> Elektrodinam volnoved struktur  Teoriya vozbuzhdeniya
> Prostr  vrem neodnor proces neupr deform metallov
> Modelirovan mehanodiffuz processov v mnogokompon 
> Matem model i eksperim issled  osn konstr geterog 
> Avtomatiz tehnol postr nestruktur raschet setok T 4
> Progr razr obr obl «Chtenie hud l»  «Kommun» v st g
> Pobeditel Sozidatel Uchitel:pamyati pr Kirillovoy
> Poryadok isp treb neimusch har  soderzh v ispol dokum 
> Effektiv metod ravnom priblizh   osnov na polinomah
> Tehnolog nasled v seriyn proizv gazoturb dvigatel 
> Rukovodstvo po sportivno funkcion klassif plovcov
> Rekomendac dlya rukovodit fizkult  ozdorov klubov
> Kompleks kontrol integral funkcion podgot futbol
> Dokument obespechen upravl deyatel v fizk organiz
> 7 Vseross nauchno praktich konfer po ekzistenc psih 
> Avtokarta: Penzenskaya Saratovskaya Tambovskaya obl 
> Pravovoe regul finansir obrazov org Vopr teor i pr
> Transform modeley prav regul obekt innovac infras
> Sovr tendenc razv zarubezh trud prava v usl globalz
> Region aspekt ekonom bezop strany v uslov globaliz
> Narodnoe predstavitelstvo Ch1 Istor teor korni tv
> Metodolog osn organiz effekt deyat po pravam chelove
> Dokumentir protivopr deyat osuzhden v ispravit uchr
> Globalnye vyzovy ustoych razvit mir ekonom Uch pos
> Vved apel poryad peresm sudeb resh po grazh i ug dela
> Analiz i ocenka deystv sist kontr realiz fed proek
> Finansovo pravov regulirov platezhn i raschet sistem
> Probl bezop oborot cifr finans aktivov v kriptoek 
> Pravov regulirov nesostoyatelnosti (bankrotstva)
> Osnov kreativ  ekzistenc obuchen inostr yazyk v neyaz
> Konceptolog v sovremenn gumanitarn issledovaniyah
> Gosudarstv regulirovan nacional ekonomiki Uchebnik
> Vnutren kontrol v upravl riskam hozyaystv subekt 
> Aktualn probl podgotov shkoln i student k profes 
> Klassnyy rukovoditel(vospitatel) Praktich  mater 
> Laboratornaya diagnost urogenit hlamidiyn infekcii
> Mnogomassht udarno volnov processy v tverdyh telah
> Lazernyy ekologichesk distancion kontrol atmosfery
> Iz istor russ perevod hudozh liter perv chetv  XIXv 
> Kombinirovan vodorodn energetichesk ciklov s atomn 
> Kompleksnaya pererab mnogokomponentn zhidkih sistem
> Adapt invar algor obnaruzh obekt v Matlab Uch p 2iz
> Osnovy energosberezheniya Uch pos 2izd
> Elektrodinamika i rasprostr radiovoln Uch pos 2izd
> Praktikum po tehnol otrasli(tehn hlebobul iz) 3izd
> Farmacevtiches himiya Fiz him metody analiza lek vesch
> Deviacii v profes socionomich tipa Teor empir issl
> Otvetstven transgr korpor grupp: teoriya i praktika
> Matematika Kurs razvit intellek reben [Metod pos]
> Ist relig tayn relig obsch obr i obych Dr mir 2 toma!
> Autizm Mify diagnostika korrekciya
> Normat pravov obesp vospit deyat v VUZah Rossii T 1
> Stihotvoreniya Poemy Stihotvoreniya v proze
> Risunki liceistov faksimil izd per vyp (1811 1817)
> Mihail Kuzmin Iskusstvo zhizn epoha+antologiya
> Regionaln mnogoobraz arhitektury russkogo barokko
> Endoskopichesk diagnost lechenie zabolevan pischevoda
> Znakomstvo s narodn izobrazit priklad iskus v DOU
> MGU imeni M V Lomonosova Sbornik spravochnik
> Mezhdunar sborn master iskusst Internat Art Masters
> UMK Lit  cht  2kl Klimanova Goreckiy Zach rab Ch2 FPU
> UMK Lit  cht  2kl Klimanova Goreckiy Zach rab Ch1 FPU
> Prog razr obr obl «Chtenie hud l»  «Kommun » sr gr 
> Progr razr obr obl «Chtenie hud l»  «Kommun»2 ml gr
> Obobschenno sopryazhen preobrazovan i integriruemost
> Kompl program adapt fizich vospit neslyshaschih detey
> Pravoslavie Literatura Revolyuciya
> Vospominan general feldmarshala knyaz Prozorovskogo
> Elegantnost zhenschin Tualet Pricheska Duhi  Krasota
> Stenogramma sudebn zasedan Specialn Sudebn Prisut
> Poln neobhod samouch domash remesel V 2 h t KOMPLEKT
> Kommerchesk encikloped Nastol spravoch kniga V 4h t 
> Ist relig tayn relig obsch obr i obych Dr mira Persiya
> Ist relig tayn relig obsch obr i obych Dr mira Indiya
> Ist relig tayn relig obsch obr i obych Dr mira Egipet
> Ist relig tayn relig obsch obr i obych Dr mir Kitay 
> Inter zapisk d/molod lyud zhelayusch sdel v obsch razvyaz 
> Illyustrirov praktichesk putevoditel po Sevastopolyu
> Illyustrir praktich putevodit po Chernomorsk poberzh 
> Iz proshlog Vospom fligel adyut Imperat Nikolaya II
> Iz zapis oruzh ohotn Kostrom guber + Ohota s damami
> Zapiski ruzheyn ohotn Orenburg gubernii
> Drevne cerkovno slovyansk yazyk  Fonetika i morfolog
> Domashn pivovar Domashn prigotovl razlich sortov piva
> Damskie mody XIXv  Istoriko hudozhestv monografiya
> Osnovy elektrotehniki Praktikum Uch pos SPO
> ANTI/Fabrika Flirt Time Anatomiya odnogo realiti
> Rassledov kontrab narkotich sredstv  perem v mezhd 
> Teoriya pravov regulir iskusstv intellekta  robotov
> Teoretich osnovy model unific grazhd zakond Rossii
> Slovar voronezh delov pism XVII–XVIIIvv T 2 (Z–M)
> Slovar voronezh delov pism XVII–XVIIIvv T 1 (A–Zh)
> Ross polit zaschit istor pravd i protiv propag fashiz
> Psihologo pedagogich soprovozhd lic s narushen sluha
> Praktich primen metod klasteriz  klassif i approks 
> Pravoslavno slavyansk civilizac v geopolit ucheniyah
> Pravovoe regulirov iskusstven intellekta  robotov
> Osoben realiz social otvet zarub korprac v Rossii
> Organiz i osuschestvl vnutr finans audita v sist MVD
> Moderniz sovremen social  ekonomich politiki Rossii
> Migrac v uslov krizisn razv mirov soobsch i ee riski
> Mezhdun stand finans otchetn dlya mal i sred predpr 
> Matematichesk modelirov investic i finansov resheniy
> Lichnostno razviv inoyazych obrazov v nachalnoy shkole
> Landshaftno ekologich issledov Moskvy dlya obosnovan 
> Konstituc  pravov osnov vneshn polit v zarub stran 
> Konkurentosp social  ekonom sistem v uslov cifrov 
> Istorichesk preemstven tradiciy rossiyskoy civiliz
> Istor i sovrem problem ekon razv Respubl Tatarstan
> Issled fenom bystrorast komp Respubl Bashkortostan
> Informac bezop finans  kredit organiz v usl cifr 
> Globaliz i institucion moderniz ekonomiiki Rossii
> Bystrodeystv odnofoton detektor na osnove tonkoy
> Aktual vopr razrab sistem uprav risk v sfer protiv
> Administrativ sudoproizvodst Uchebnik dlya bakalavr 
> Anatomiya cheloveka Angiologiya KARTOChKI (45sht)
> Prenataln diagnostik nasledstven bolezney 3 e izd
> Emocion vygoran rodstven bolnyh s himich zavisim 
> Uspeshnaya neustoychiv industrializac mira: 1880–1913
> Ochischen nacii Nasilstv peremesch nasel i etich chistki
> Antibulling Dop progr prof bullinga 11 13l Met rek
> Pronikn krupn ross finans kapital v ekonom Sr Azii
> Endoskopichesk diagnost lechenie zabolev tolst kishki
> Psihologicheskoe vozdeystvie:Mehanizmy strategii
> Pravila promysh bezop opas pr obek rab pod izb dav
> Metodika ekspert issled deyat kredit potreb kooper
> Korporat konflikty oslozh inostr elemen i ih razresh
> «Mashina vlasti» v virt prostranstve(formir obraza)
> Publichno chastn partnerst Rossii i zarubezh stranah
> Normat pravov obesp molod polit v VUZah Rossii T 2
> Integrir predmetn diagnostich rab 1kl Metod pos
> Angliysk yazyk Nab kart cv ch "V" V kabinete u vracha
> Lyubimye zhenschiny Povesti rasskazy esse
> Obuchenie doshkol sostavl logichesk rasskaz po serii
> Psihologo pedagog soprov razvit rebenka v detskom
> Tochki Linii Figury Prost geometr ponyat D/det 5 7l
> Lesopilno derevoobrabatyvayuschie proizvodstva lesozagotovitelnyh predpriyatiy
> Tehnologiya lesopilno derevoobrabatyvayuschih proizvodstv  Tehnologicheskie raschety proizvodstvennoy moschnosti  Uchebnoe posobie
> Organizacionno tehnologicheskoe proektirovanie potochnogo stroitelstva  Uchebnoe posobie
> Kompleksnoe mediko psihologo pedagogicheskoe soprovozhdenie lic s ogranichennymi vozmozhnostyami zdorovya v usloviyah nepreryvnogo inklyuzivnogo obrazovaniya
> Organizacionno tehnologicheskoe proektirovanie uchastkov i cehov  Uchebnoe posobie  Grif UMO vuzov RF
> Kompetentnostno orientirovannyy urok  Celepolaganie  Proektirovanie  Ocenka effektivnosti  FGOS
> ASP SZR Pravonarushitelnicy Zhenskaya prestupnost i kriminalogiya v Rossii (1880 1930)
> Samodiysko tunguso manchzhurskie leksicheskie svyazi
> Atlas dlya eksperimentalno psihologicheskogo issledovaniya lichnosti
> Informacionno kommunikacionnaya koncepciya teorii buhgalterskogo ucheta
> Eksperimentalno psihologicheskoe issledovanie v psihiatrii  Uchebnoe posobie
> Racionalno emotivno povedencheskaya terapiya
> Devochkadevochkadevochkadevochka
>

**Comment by PrzemyslawLukanowski** [comment] 2022-10-27 11:42
Thank you for the list. I will let you know when we change the names of the products to valid ones.

**Comment by PrzemyslawLukanowski** [comment] 2022-10-28 09:27
We have changed the names of those products, so you should be able to list offers now.

**Closed** 2022-11-12 14:15 UTC
Labels: sandbox, brak_odpowiedzi

**Comment by din1s** [comment] 2022-11-16 05:27
Good afternoon!
Thank you, everything is fine with the addition of goods.

Now there is a question about price updates and the availability of goods - you can update the price for a trade offer via PUT /offers/{offerId}/change-price-commands/{commandId}, but what about the availability of goods? Update prices and product availability at the same time via PATCH /sale/product-offers/{offerId}?

**Comment by PrzemyslawLukanowski** [comment] 2022-11-16 07:09
Yes, you can make it with the same single request via PATCH /sale/product-offers/{offerID}, but please remember that you cannot change the stock to "0", so instead you can change the status of the offer to "ENDED":

```
{
    "publication": {
        "status": "ENDED"
    }
}
```

And when the goods will be once again available, then you can change the status to "ACTIVE" , along with the stock and price to the proper values:

```
{
    "stock": {
        "available": 10,
        "unit": "UNIT"
    },
    "publication": {
        "status": "ACTIVE"
    },
        "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "420.85",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    }
}


```

**Comment by din1s** [comment] 2022-11-16 07:15
This is how we update now.
But the problem is that we update prices and stocks of all goods several times a week. It will take us several days to completely update all the products in your system. Is there any way to update prices and balances faster? Maybe a batch update?

**Comment by PrzemyslawLukanowski** [comment] 2022-11-16 07:30
We have the possibility to [modify offers in bulk](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3), for example, you can activate or end up to 1000 offers per single request. In case of changing stock or prices, you can also edit a maximum of 1000 offers, but in this case, you can pass only one price/stock for all those offers.

**Comment by din1s** [comment] 2022-12-06 07:46
Good afternoon.
In the course of work, another question arose - can you tell me at what point in placing / paying for an order in your system, the client can change the delivery method?

**Comment by PrzemyslawLukanowski** [comment] 2022-12-06 07:56
After adding products to the cart and selecting the "delivery and payment" option, the buyer will be redirected to the delivery and payment form - here it is possible. [Here](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/czym-jest-formularz-dostawy-i-platnosci-D5AgVlYv8tq) you can find more information.
