### ISSUE TITLE
API - category, SandBox test orders

### ISSUE THREAD

**Issue by BarnetMichal** [allegro/allegro-api#7810] opened 2023-10-19 09:58 UTC
Hi,

1, What for is the attribute offersWithProductPublicationEnabled in category options? If I create a product and an offer via endpoint 'sale/product-offers' what categories can I use? The ones with 'offersWithProductPublicationEnabled = true and productCreationEnabled = true'?

2, Is there any validation for a duplicate offer? I managed to create several duplicate offers on my sandbox account. 

3, Is it possible to create a test order for my offer on the sandbox account? I have active offers but I can't see them from another account and I can't create an order from the same account. 
My account is under michal.b@koongo.com

Thank you.

**Comment by Lukasz-Zurek** [comment] 2023-10-19 11:44
1. Yes.
2. No, but on October 16, 2023 we have introduced changes related to limiting the number of offers that can be connected with a single, same product and in selected categories, you can associate up to 5 offers. You will find more information in our latest [news](https://developer.allegro.pl/news/in-selected-categories-you-will-list-maximally-5-offers-of-the-same-product-ZMqZ2KbZPsw).
3. Please create another account for purchase purposes. It will be useful for many future test transactions. If you have any problem with activation process, please let me know.

**Comment by BarnetMichal** [comment] 2023-10-20 10:57
I created a new account with the email 'team@koongo.com'. Can you please activate this account, I`m stuck on  'bank and transfer PLN 1.01 to us to confirm' page.

I have one more question about the image update. If I update e.g. images via the endpoint 'products/id/change-proposals', do I have to update the offers assigned to this product or is the product change also transferred to offers?

Thank you.

**Comment by Lukasz-Zurek** [comment] 2023-10-20 12:18
@BarnetMichal I see that your account has been registered on the production, so I cannot help you, but I see that it has been already activated, is everything ok now? If not - please use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc).

Regarding your second question - if the product is updated with new images - your offers which are assigned to this product - will not be updated automatically. You will be able to update your offer with the new product's data (and images) while editing the offer with [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) resource.

**Comment by BarnetMichal** [comment] 2023-10-20 12:29
I used the same email for the Sandbox account. Client:106204472, team@koongo.com. With the production account is everything ok, what I need is to activate the sandbox account.

**Comment by BarnetMichal** [comment] 2023-10-20 13:29
Ok, I think there's been a misunderstanding.
I already have a sandbox business account registered as michal.b@koongo.com.
What I want to achieve is to create a test order for the offer that I added via my business account (michal.b@koongo.com). You suggested in your first reply, point 3 - 'Please create another account for purchase purposes.' so I did, I created a new account team@koongo.com and I need to activate it, so I can create test orders, right?

**Comment by Lukasz-Zurek** [comment] 2023-10-23 05:40
@BarnetMichal Yes. Ok, everything is clear now. I have activated your account [team@koongo.com](mailto:team@koongo.com).

**Comment by BarnetMichal** [comment] 2023-10-23 11:34
super, thank you.

Can you please help me with this validation error? Is there a way to get a valid EAN in the category? 

{"errors":[{"code":"ProductValidationException","message":"Invalid GTIN: 225693 - 0889423514880 in category: 87913","details":null,"path":"productSet[0].product","userMessage":"Incorrect value for EAN (GTIN) parameter."}]} in https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

My request payload:

{"productSet":[{"product":{"id":"0889423514880","idType":"GTIN","category":{"id":"87913"},"name":"Hummingbird printed t-shirt","images":["http:\/\/p17.devel1.nostresscommerce.cz\/1-large_default\/image.jpg|http:\/\/p17.devel1.nostresscommerce.cz\/2-large_default\/image.jpg"],"parameters":[{"name":"Brand","values":["10K"]},{"name":"Size","values":["XS"]},{"name":"Color","values":["beige"]},{"name":"Main Pattern","values":["plain"]},{"name":"Neckline","values":["curved"]},{"name":"Main Fabric","values":["silk"]}]}}],"delivery":{"shippingRates":{"id":"d787a2cf-d0c3-4e45-857a-339483012dad"}},"images":["http:\/\/p17.devel1.nostresscommerce.cz\/1-large_default\/image.jpg|http:\/\/p17.devel1.nostresscommerce.cz\/2-large_default\/image.jpg"],"parameters":[],"name":"Hummingbird printed t-shirt","stock":{"unit":"UNIT","available":"2041"},"category":{"id":"87913"},"sellingMode":{"price":{"currency":"USD","amount":"19.88"}},"language":"en-US"}

**Comment by Lukasz-Zurek** [comment] 2023-10-23 12:23
This EAN is incorrect (it has an invalid checksum). On the production GTIN/EAN should be compatible with https://www.eprodukty.gs1.pl/catalog database.

**Comment by BarnetMichal** [comment] 2023-10-24 13:30
Okay, thanks. I found a valid EAN and it works. 

I would like to ask about the validation of the offer description attribute. Is there somewhere a description of what HTML elements I can insert or how to structure this attribute? And if I want to insert text, image, and text, in that order I have to insert 3 objects into the items attribute?

**Comment by Lukasz-Zurek** [comment] 2023-10-25 11:56
@BarnetMichal I am sorry for my late answer. You can find all of these information in our [guide](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty). We have marked which HTML tags can you use, together with description structure and images.

**Closed** 2023-11-12 10:10 UTC
Labels: productization, offer, brak_odpowiedzi

**Comment by kndnooo** [comment] 2024-02-20 10:28
Hello,
i have problem with my request who adding item to category toys (trace-id: d2ca9de50e3d4084)
The problem is i have error from server when execute this
`curl -v -X POST https://api.allegro.pl.allegrosandbox.pl/sale/product-offers -H 'Authorization: Bearer ' -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Content-Type: application/vnd.allegro.public.v1+json' -d '{ "productSet": [ { "product": { "name": "Roadmax Traktor z łyżką Bruder 20102", "category": { "id": "86352" }, "images":[ "https://good_link.jpg" ], "parameters": [ { "id":"3475","valuesIds":["3475_1"] }, { "id":"127812","valuesIds":["127812_384253"] }, { "id":"127768","valuesIds":["127768_71"],"values":["inny"], "rangeValue":null }
, { "id":"18136","valuesIds":["18136_4"] } ] }, "quantity": { "value": 1 } } ], "afterSalesServices": { "impliedWarranty": { "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59", "name": "string" }, "returnPolicy": { "id": "09f0b4cc-
7880-11e9-8f9e-2a86e4085a59", "name": "string" }, "warranty": { "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59", "name": "string" } }, "parameters": [ {"id":"11323","valuesIds":["11323_1"] } ] }'`
Now day i get response `{"errors":[{"code":"ProductValidationException","message":"ConstraintViolationException.RequireEnabledCategory","details":null,"path":"productSet[0].product","userMessage":"Dodawanie produktów do kategorii nie jest możliwe."}]}`
but two days ago i was get error 500 type from server.
What i make wrong or what fields i forgot add in my api-request ? Greetzing

**Comment by kndnooo** [comment] 2024-02-20 14:00
ok, i resolve problem, use category id 86356. Thanks.
